### ISSUE TITLE
Making sense of dphysics::ParticleSystem::Update

### ISSUE THREAD

**Issue by Andersama** [ange-yaghi/delta-studio#36]
Looking at the code you've got:
```c
    int n = (rand() % (100)) < 100; // Get a random number centered on the mean
    
    for (int i = 0; i < n; i++) {
        Particle *newParticle = m_particles.NewGeneric<Particle, 16>();
        newParticle->m_age = 0.0f;
        newParticle->m_life = ((rand() % 100) / 100.0f) + 5.0f;
        newParticle->m_texture = m_texture;
        newParticle->m_damping = 0.98f;
        newParticle->m_scale = 0.0f;
        newParticle->m_expansionRate = (rand() % 100) / 100.0f;
        newParticle->SetParent(this);
        newParticle->m_velocity = ysMath::LoadVector(float((rand() % 200) - 100), float((rand() % 200) - 100), 0.0f);
        newParticle->m_position = ysMath::Constants::Zero;
        newParticle->m_density = ((rand() % 200 - 100) / 800.0f) + 0.2f;
    }
```
Not sure if this is intended but the `< 100` turns the expression before into a bool, and since `% 100` results in values 0-99 you'll have essentially:
```
int n = 1;
for (int i = 0; i < 1; i++) {
```
I don't picture that's what you were after, because you could easily have rewritten that as an if...or just:
```
        Particle *newParticle = m_particles.NewGeneric<Particle, 16>();
        newParticle->m_age = 0.0f;
        newParticle->m_life = ((rand() % 100) / 100.0f) + 5.0f;
        newParticle->m_texture = m_texture;
        newParticle->m_damping = 0.98f;
        newParticle->m_scale = 0.0f;
        newParticle->m_expansionRate = (rand() % 100) / 100.0f;
        newParticle->SetParent(this);
        newParticle->m_velocity = ysMath::LoadVector(float((rand() % 200) - 100), float((rand() % 200) - 100), 0.0f);
        newParticle->m_position = ysMath::Constants::Zero;
        newParticle->m_density = ((rand() % 200 - 100) / 800.0f) + 0.2f;
```
You also calculated:
```c
float expected = m_rate * timeStep;
```
Which I'm guessing is roughly how many particles you wanted to spawn in the timeframe, and that you wanted to try to randomly spawn them at different time frames so each update wouldn't be a continuous stream of new particles?

**Comment by ange-yaghi** [comment]
This code is ancient and could well have been written over 10 years ago when I was still in high school. I have no idea what I was intending with it or what I was trying at that time. It was probably just meant to be a random test I was messing with that I left in the code for some reason. Anyway, I don't recommend looking too closely into this code because it's obviously a mess, but I appreciate the concern. I might fix this but I'm doing a clean rewrite of this engine for my next game project so for all intents and purposes, it's deprecated. Thankfully my present self would be able to write a much more coherent particle system than this.

**Comment by Andersama** [comment]
You wrote most of this a decade ago? Ignore me then, was curious obviously because of the youtube videos. The repo looked somewhat current so I think at the time I thought you might've been working off this one.

**Comment by ange-yaghi** [comment]
I do still use it and the parts that work, work well enough. The whole codebase is a mess though, it's just a sandbox I've been using for years.

**Comment by Andersama** [comment]
Ah well it's a pretty neat mess. I don't remember what exactly what I was doing, I think I just looked around the source code and then got genuinely confused by this part.
